Convert worlds to ENU
cyberbotics/webots_ros pull request #38
Opened 2020-11-02 10:59 UTC by lukicdarkoo

- [x] Convert worlds to ENU
- [ ] Fix IMU usage (sync with Webots `develop`)
- [x] Fix GPS usage (sync with Webots `develop`)
- [ ] Upgrade Webots headers

2020-11-02 17:30 UTC, lukicdarkoo commented
At this point, it solves all issues from:
https://github.com/cyberbotics/webots_ros/issues/37

We can merge it after https://github.com/cyberbotics/webots/pull/2424 is merged (and maybe some cleanup)

2020-11-04 15:59 UTC, omichel requested changes

2020-11-04 15:59 UTC, omichel commented on src/pioneer3at.cpp
> +static double GPSValues[3] = {0, 0};
That looks wrong...
```suggestion
static double GPSValues[2] = {0, 0};
```

2020-11-04 16:06 UTC, lukicdarkoo commented on src/pioneer3at.cpp
> +static double GPSValues[3] = {0, 0};
It is :)

2020-11-04 16:11 UTC, omichel approved these changes
All good. Thanks.

2020-11-04 16:14 UTC, merged