Conversion enu for webots ros
cyberbotics/webots_ros pull request #86
Opened 2021-10-26 10:33 UTC by BenjaminHug8

This PR has the goal to convert worlds and cpp files in order to be compatible with 2021c.

- [x] Convert worlds
- [x] Convert scripts

2021-11-09 14:45 UTC, BenjaminHug8 commented
@ad-daniel May I ask you to distribute the review of this PR please?

2021-11-09 16:37 UTC, joachimhgg requested changes
Thanks ! Just a few minors changes.

-catch_the_birds:
    - wrong orientation of the body of the bird
- complete_test:
     - an extra cone and a person in robots have been added.
     - the robot and the cube are not FLU (Z up)
     - the RADAR_TARGET is not at the good location
- epuck_line:
    - obstacles are not FLU (change box size from size 1 2 3 to size 3 1 2 )
- pioneer3at:
    - EXTERNAL_WALL INTERNAL_WALL are not flu. (change box size + rotation)
    - rotations need to be cleaned. You can use the script `scripts/converter/convert_nue_to_enu_rub.py` and change the mode by 'clean' to clean all the rotations.
- tiago:
    - e-puck is not at the good location
    - worktops and walls are not flu
    - rotations need to be cleaned

2021-11-09 16:37 UTC, joachimhgg commented on worlds/keyboard_teleop.wbt
> +  rotation 1 0 0 0
```suggestion
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
>    size 22.4 2.4 0.2
```suggestion
  translation 0 0 30
  rotation 0 1 0 1.5708
  size 0.2 22.4 2.4
```
something like this. Need to be done for the external walls.

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation -7.19235e-09 7.19235e-09 -1 1.5708
```suggestion
  rotation 0 0 -1 1.5708
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation -5.51888e-09 7.19235e-09 -1 1.8326
```suggestion
  rotation 0 0 -1 1.8326
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +      rotation 1 -1.72486e-06 -6.88391e-07 -1.5707953071795862
```suggestion
      rotation 1 0 0 -1.5707953071795862
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +      rotation 1 -1.72486e-06 -6.88391e-07 -1.5707953071795862
```suggestion
      rotation 1 0 0 -1.5707953071795862
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +      rotation -0.9999999999944038 8.636279999951669e-07 3.2321499999819125e-06 1.57079
```suggestion
      rotation -1 0 0 1.57079
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation -7.19235e-09 -7.19235e-09 1 1.5708
```suggestion
  rotation 0 0 1 1.5708
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation -7.19235e-09 7.19235e-09 -1 1.5708
```suggestion
  rotation 0 0 -1 1.5708
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation -7.19235e-09 -7.19235e-09 1 1.5708
```suggestion
  rotation 0 0 1 1.5708
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation -7.19235e-09 7.19235e-09 -1 1.5708
```suggestion
  rotation 0 0 -1 1.5708
```

2021-11-09 16:37 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +      name "desk(30)"
```suggestion
      name "desk(15)"
```

2021-11-10 09:21 UTC, BenjaminHug8 commented
I changed the Kitchen in flu in `pioneer3at.wbt`.

2021-11-11 15:39 UTC, joachimhgg requested changes
Thanks. Just a few more comments.
- catch_the_birds: 
  - wrong bounding box
- complete_test:
![image](https://user-images.githubusercontent.com/48200998/141323136-9a472e7e-33ca-4fef-9bfe-b3abd0699fe5.png)
2021b version:
![image](https://user-images.githubusercontent.com/48200998/141323353-bdc5ef05-cc79-459a-a674-6b8f779a5213.png)

- the robot miss a -pi/2 on z to be FLU.
- the Solid (the box) is not FLU.
- you can delete the rotation on the RADAR_TARGET to be FLU

2021-11-11 15:39 UTC, joachimhgg commented on worlds/catch_the_bird.wbt
> +          physics Physics {
![image](https://user-images.githubusercontent.com/48200998/141321315-1f1f22b7-1dcf-45bc-ba89-f69c0ed52398.png)

you added an extra bounding object, physics node and name

2021-11-11 15:39 UTC, joachimhgg commented on worlds/complete_test.wbt
> +  rotation 1 0 0 0
```suggestion
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/complete_test.wbt
> +      rotation 0.707107781185531 1.695249475405131e-09 0.70710578118615 -3.1415853071795863
```suggestion
      rotation 0.707107781185531 0 0.70710578118615 -3.1415853071795863
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation 0 0 -1 -2.356185307179586
```suggestion
  rotation 0 0 1 2.356185307179586
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation -1 0 0 -1.5707953071795862
```suggestion
  rotation 1 0 0 1.5707953071795862
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/pioneer3at.wbt
> +  rotation 0 0 -1 -1.5707953071795862
```suggestion
  rotation 0 0 1 1.5707953071795862
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/tiago.wbt
> +  rotation 0 0 -1 -1.5707853071795865
```suggestion
  rotation 0 0 1 1.5707853071795865
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/tiago.wbt
> +  rotation 0 0 -1 -3.141495307179586
```suggestion
  rotation 0 0 1 3.141495307179586
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/tiago.wbt
> +  rotation 0 0 -1 -3.141495307179586
```suggestion
  rotation 0 0 1 3.141495307179586
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/tiago.wbt
> +  rotation 0 0 -1 -1.5707953071795862
```suggestion
  rotation 0 0 1 1.5707953071795862
```

2021-11-11 15:39 UTC, joachimhgg commented on worlds/tiago.wbt
> +  rotation 0 0 -1 -1.5707953071795862
```suggestion
  rotation 0 0 1 1.5707953071795862
```

2021-11-12 10:50 UTC, BenjaminHug8 commented
For the `catch_the_bird`, due to the change of orientation of the cylinders I have no choice than add `Transform` nodes.

2021-11-15 13:42 UTC, joachimhgg commented
complete_test: The range finder needs to be turn as well

2021-11-15 14:04 UTC, joachimhgg approved these changes

2021-12-16 15:30 UTC, merged