Add web stream parameters
cyberbotics/webots_ros pull request #90
Opened 2021-11-26 08:17 UTC by CumaOzavci

2021-11-26 17:38 UTC, lukicdarkoo requested changes
Thank you! It's indeed a missing option.

However, I would rather keep the Webots format to keep consistency. That way we can simply redirect users to the official Webots documentation. What do you think?

2021-11-29 07:44 UTC, CumaOzavci commented
I fixed consistency issues. I did not notice python version change, it must be the IDE i am using. Also i restored default values of all parameters. It should work like before now.

Keeping code simple is a great idea but i would prefer to access all Webots parameters with simple roslaunch arguments.

2021-12-01 14:37 UTC, lukicdarkoo commented
They still would be accessible, for example:
```
roslaunch webots_ros tiago.launch mode:="port=1234,mode=x3d,monitorActivity"
```

2021-12-10 11:29 UTC, lukicdarkoo commented
> They still would be accessible, for example:
> 
> ```
> roslaunch webots_ros tiago.launch mode:="port=1234;mode=x3d;monitorActivity"
> ```

Hello @CumaOzavci, do you agree on this? And, is it clear what we want to achieve? If you don't have time I can implement it.

2021-12-13 09:58 UTC, CumaOzavci commented
Hi @lukicdarkoo, sorry for late reply. I was on vacation.



> They still would be accessible, for example:
> 
> ```
> roslaunch webots_ros tiago.launch mode:="port=1234;mode=x3d;monitorActivity"
> ```


I tought you were implying that **with current implementation**, they still would be accessible. Upon checking the code again, i see what you mean.

Passing all stream parameters as one string is a clever solution. I can implement it. I will commit changes this week.

By the way "mode" parameter name is already being used. I think we should name new parameter "stream" like this: 
`roslaunch webots_ros tiago.launch stream:="port=1234;mode=x3d;monitorActivity"
`

2021-12-13 12:48 UTC, lukicdarkoo commented
@CumaOzavci

> I tought you were implying that with current implementation, they still would be accessible. Upon checking the code again, i see what you mean.

Sorry for the confusion :/

> Passing all stream parameters as one string is a clever solution. I can implement it. I will commit changes this week.

Perfect, thanks!

> By the way, "mode" parameter name is already being used. I think we should name new parameter "stream", like this:

Yes, you are right, the `stream` argument is much better, my bad.

2021-12-15 10:50 UTC, CumaOzavci commented
@lukicdarkoo 

As you requested, i simplified web stream parameters.

Please check commits.

2021-12-16 11:47 UTC, lukicdarkoo requested changes
Great! 

I would change a small detail. If a user does:
```
roslaunch webots_ros tiago.launch stream:=""
```
then it should run the streaming with default parameters

2021-12-16 11:47 UTC, lukicdarkoo commented on launch/webots.launch
> +  <arg name="stream" default="" doc="Start Webots streaming server"/>
```suggestion
  <arg name="stream" default="false" doc="Start Webots streaming server"/>
```

2021-12-16 11:47 UTC, lukicdarkoo commented on scripts/webots_launcher.py
> +optParser.add_option("--stream", dest="stream", default="", help="Start Webots streaming server.")
```suggestion
optParser.add_option("--stream", dest="stream", default="false", help="Start Webots streaming server.")
```

2021-12-16 11:47 UTC, lukicdarkoo commented on scripts/webots_launcher.py
> +if options.stream != '':
```suggestion
if options.stream != 'false':
```

2021-12-17 09:40 UTC, CumaOzavci commented
@lukicdarkoo

> Great!
> 
> I would change a small detail. If a user does:
> 
> ```
> roslaunch webots_ros tiago.launch stream:=""
> ```
> 
> then it should run the streaming with default parameters

That's a good idea but roslaunch gives "false" value to parameters passed with "". 

Therefore i suggest this:
   1. Stream parameter should have "false" as default value. If user does not use it, streaming won't work.
   2. If user wants to stream with default values, he/she should set stream argument to "true".
   3. If user wants to stream with custom values, he/she should set stream argument to custom streaming string, like "port=4567;mode=mjpeg"

2021-12-17 09:52 UTC, lukicdarkoo approved these changes
Thank you!

2021-12-20 07:22 UTC, omichel commented
@CumaOzavci: I just sent you an invite via GitHub to become a member of the Webots committers, so that you should be able to merge this PR yourself by pressing the "Merge pull request" button.

2021-12-20 09:28 UTC, merged

2021-12-20 09:56 UTC, CumaOzavci commented
@omichel, thank you for adding me to Webots Committers.


As Saha Robotik, we are testing Webots for future projects. So far we are impressed with results, especially with multi robot simulations.

![playground](https://user-images.githubusercontent.com/17505356/146746172-ed1b639b-78ba-4a94-b206-5258e9bbc8b1.png)

You can expect more PRs like this, as we go further with Webots.